name: Release

on:
  push:
    branches:
      - 'main'
      - 'pdfRendering'
  workflow_dispatch:

env:
  REGISTRY_HOSTNAME: ghcr.io
  IMAGE_NAME: vunetsystems/renderer

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ### DOCKER SECTION
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=pr
            type=ref,event=branch
            type=raw,value=b${{ github.run_number }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
